[tool.mypy]
python_version = "3.10"
warn_return_any = false
warn_unused_configs = true
ignore_missing_imports = true

[tool.ruff]
select = ["E", "F", "B"]
ignore = ["E501"]

# Assume Python 3.10.
target-version = "py310"

[tool.isort]
py_version = 310
skip_gitignore = true
line_length = 120
multi_line_output = 3
lines_after_imports = 2
force_alphabetical_sort_within_sections = true
profile = 'black'
