name: Run mypy / pylint

on:

  push:
    branches:
      - main

  pull_request:
    branches:
      - main


jobs:
  
  linting:
    
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code
        uses: actions/checkout@v2.4.2

      - name: Install Python 3
        uses: actions/setup-python@v3.1.2
        with:
          python-version: '3.10.0'

      - name: Upgrade Pip / Install Dependancies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run mypy
        run: |
          yes | mypy ./pisr --install-types || true
          mypy ./pisr
      - name: Run pylint
        run: pylint ./pisr

